[package]
name = "datasetfuse_bindings"
version = "0.1.0"
edition = "2018"
authors = ["dheeraj-msft"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "*"

[lib]
name="datasetfuse_bindings"
crate-type = ["cdylib"]
